on:
  push:
    branches: main

name: Render and publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
        env:
          # The US election story needs an increased call stack size, not sure why
          QUARTO_DENO_EXTRA_OPTIONS: --v8-flags=--stack-size=2048

      - name: Upload files to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
